version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8002:8002"
    environment:
      - COA_DEBUG=false
      - COA_LLM_ENABLED=true
      - COA_LLM_BASE_URL=http://192.168.4.13:8080/v1
      - COA_LLM_API_KEY=sk-mi-ia-secreta
      - COA_CORS_ORIGINS_CSV=http://localhost:8501
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002

  dashboard:
    build: .
    ports:
      - "8501:8501"
    environment:
      - COA_API_BASE_URL=http://backend:8002
    command: streamlit run app/ui/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - backend
